version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres_sql_filhos
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: filhos123
      POSTGRES_DB: filhos
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
