spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/filhos
    username: admin
    password: filhos123
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  mail:
    host: smtp.gmail.com
    port: 587
    username: suprifilhos@gmail.com
    password: imes aqna gjco giop
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


logging:
  level:
    org:
      springframework:
        web: DEBUG
