spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/filhos
    username: admin
    password: filhos123
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

logging:
  level:
    org:
      springframework:
        web: DEBUG
